import { type AppType } from "next/app";
import { api } from "~/utils/api";
import "~/styles/globals.css";
import Head from "next/head";
import { SessionProvider } from "next-auth/react";
import { type Session } from "next-auth";

const MyApp: AppType<{ session: Session | null }> = ({ 
  Component, 
  pageProps: { session, ...pageProps} }) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Roadmap Investidor</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/money-svgrepo-com.svg" />
      </Head>
      <Component {...pageProps} />
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
